name: counter
description: store builder example

version: 0.3.0+1

dependencies:
  flutter:
    sdk: flutter
  store_builder:
    path: ../../../flutter-store-builder

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ^1.2.0
